=== FanJiGang/project01/xml/resources/teacher.xsd
<?xml version="1.0" encoding="utf-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/teacher"
        elementFormDefault="qualified">

    <element name="teachers">
        <complexType>
            <sequence maxOccurs="unbounded">
                <element name="teacher">
                    <complexType>
                        <sequence>
                            <element name="name" type="string" ></element>
                            <element name="age" type="int"></element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>


</schema>

=== FanJiGang/project01/xml/resources/teacher.xml
<teachers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.example.org/teacher"
    xsi:schemaLocation="http://www.example.org/teacher teacher.xsd">
    <teacher>
        <name>马什么梅</name>
        <age>23</age>
    </teacher>
    <teacher>
        <name>马冬什么</name>
        <age>25</age>
    </teacher>
    <teacher>
        <name>什么冬梅</name>
        <age>21</age>
    </teacher>
</teachers>
